apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle18c 
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.3.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 18.3.0.1
  template:
    metadata:
      name: oracle18c
      labels:
        app: database
        version: 18.3.0.1
    spec:
      securityContext:
        fsGroup: 54321
      volumes:
         - name: dshm
           emptyDir:
             medium: Memory  
         - name: ora-data183
           persistentVolumeClaim:
             claimName: ora-data183
         - name: ora-startup183
           persistentVolumeClaim:
             claimName: ora-setup183
         - name: ora-setup183
           persistentVolumeClaim:
             claimName: ora-startup183
      containers:
        - name: oracle18c
          image: registry:32000/oracledb:18.3.0-ee
          command:
          - /opt/oracle/runOracle.sh
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 8Gi
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
             - name: dshm
               mountPath: "/dev/shm"
             - name: ora-data183
               mountPath: "/opt/oracle/oradata"
             - name: ora-setup183
               mountPath: "/opt/oracle/scripts/setup"
             - name: ora-startup183
               mountPath: "/opt/oracle/scripts/startup"
          env:
            - name: ORACLE_SID
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_SID #Read the key call ORALCE_SID
            - name: ORACLE_PDB
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PDB #Read the key call ORACLE_PDB
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PWD #Read the key call ORACLE_PWD
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_CHARACTERSET #Read the key call ORACLE_CHARACTERSET
---
### Oracle 18c
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-data183
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.3.0.1
spec:
  storageClassName: pure-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-startup183
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.3.0.1
spec:
  storageClassName: pure-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-setup183
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.3.0.1
spec:
  storageClassName: pure-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oracle18c
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.3.0.1
spec:
  selector:
    app: database
    version: 18.3.0.1
  type: NodePort
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oemexpress
    protocol: TCP
    port: 5500
    targetPort: 5500
