kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-ora-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "db"
   priority_io: "high"
---
apiVersion: v1
kind: Namespace
metadata:
  name: oracle-namespace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle19c 
  namespace: oracle-namespace
  labels:
    app: database
    version: 19.3.0.1
spec:
  serviceName: "oracle19c"
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 19.3.0.1
  template:
    metadata:
      name: oracle19c
      labels:
        app: database
        version: 19.3.0.1
    spec:
      securityContext:
        fsGroup: 54321
      volumes:
         - name: dshm
           emptyDir:
             medium: Memory
      imagePullSecrets:
        - name: regcred 
      containers:
        - name: oracle19c
          image: container-registry.oracle.com/database/enterprise:19.3.0.0
          command:
          - /opt/oracle/runOracle.sh
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 2Gi
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: ora-data193
              mountPath: "/opt/oracle/oradata"
            - name: ora-setup193
              mountPath: "/opt/oracle/scripts/setup"
            - name: ora-startup193
              mountPath: "/opt/oracle/scripts/startup"
          env:
            - name: ORACLE_SID
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_SID #Read the key call ORALCE_SID
            - name: ORACLE_PDB
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PDB #Read the key call ORACLE_PDB
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PWD #Read the key call ORACLE_PWD
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_CHARACTERSET #Read the key call ORACLE_CHARACTERSET
  volumeClaimTemplates:
  - metadata:
      name: ora-startup193 
    spec:
      storageClassName: px-ora-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-setup193
    spec:
      storageClassName: px-ora-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-data193
    spec:
      storageClassName: px-ora-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oracle19c
  namespace: oracle-namespace
  labels:
    app: database
    version: 19.3.0.1
spec:
  selector:
    app: database
    version: 19.3.0.1
  type: NodePort
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oemexpress
    protocol: TCP
    port: 5500
    targetPort: 5500
