---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: ora-data183-snap
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.3.0.1
spec:
  snapshotClassName: pure-snapshotclass
  source:
    name: ora-data183
    kind: PersistentVolumeClaim
